name: NASA Project CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    env:
      CI: true
    strategy:
      matrix:
        node-version: [16.x, 20.x]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install backend dependencies (with devDependencies)
      working-directory: server
      run: npm install --include=dev

    - name: Run backend tests
      working-directory: server
      run: npm test

    - name: Install frontend dependencies
      working-directory: client
      run: npm install

    - name: Build frontend
      working-directory: client
      run: npm run build
